Notebook for plotting the results of the study

First, we load the data and we structure it in a nested dictionary

In [49]:
import pandas as pd 

names = {'td2c':'TD2C', 
         'td2c_cmiknn':'TD2C - CMIKNN', 
         'pcmci': 'PCMCI', 
         'granger': 'Granger', 
         'dyno': 'DYNOTEARS', 
         'varlingam': 'VARLiNGAM'}

def flatten_metric_dict(method, metric_dict):
    items = pd.DataFrame(columns=['Model','dataset_name','Score'])
    for process_idx, subdict in metric_dict.items():
        for observation_idx, subsubdict in subdict.items():
            items.loc[len(items)] = [names[method], str(process_idx)+'_'+str(observation_idx), subsubdict]
    print(items.shape)
    return items

In [50]:
import pickle
rocs_flattened = {}
precisions_flattened = {}
recalls_flattened = {}
f1s_flattened = {}
for N in [5, 10, 25]:
    rocs_flattened[N] = pd.DataFrame(columns=['Model','dataset_name','Score'])
    precisions_flattened[N] = pd.DataFrame(columns=['Model','dataset_name','Score'])
    recalls_flattened[N] = pd.DataFrame(columns=['Model','dataset_name','Score'])
    f1s_flattened[N] = pd.DataFrame(columns=['Model','dataset_name','Score'])
    for method in ['td2c', 'td2c_cmiknn', 'pcmci', 'granger', 'dyno', 'varlingam']:
        if method == 'varlingam' and N == 25:
            continue
        with open(f'journal_results_{method}_N{N}.pkl', 'rb') as f:
            rocs_dict, precision_dict, recall_dict, f1_dict = pickle.load(f)

        rocs_flattened[N] = pd.concat([rocs_flattened[N], flatten_metric_dict(method, rocs_dict)])
        precisions_flattened[N] = pd.concat([precisions_flattened[N], flatten_metric_dict(method, precision_dict)])
        recalls_flattened[N] = pd.concat([recalls_flattened[N], flatten_metric_dict(method, recall_dict)])
        f1s_flattened[N] = pd.concat([f1s_flattened[N], flatten_metric_dict(method, f1_dict)])
    
    rocs_flattened[N] = rocs_flattened[N].dropna().reset_index(drop=True)
    precisions_flattened[N] = precisions_flattened[N].dropna().reset_index(drop=True)
    recalls_flattened[N] = recalls_flattened[N].dropna().reset_index(drop=True)
    f1s_flattened[N] = f1s_flattened[N].dropna().reset_index(drop=True)

(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)
(720, 3)


In [51]:
import sys
import os
import pandas as pd
import numpy as np

from d2c.benchmark.cd_plot import draw_cd_diagram


The function expects a dataframe as follows 

| dataset_name   |      Model      |  Score |
|----------|:-------------:|------:|
| 1 |  d2c | 0.7 |
| 2 |    var   |  0.55 |
| 3 | dynoteas |    0.65 |


In [52]:
for n_var in [5,10,25]:
    draw_cd_diagram(f'figures/cd_rocs_{n_var}.png', df_perf=rocs_flattened[n_var], title='ROC-AUC', labels=False)
    draw_cd_diagram(f'figures/cd_precisions_{n_var}.png', df_perf=precisions_flattened[n_var], title='Precision', labels=False)
    draw_cd_diagram(f'figures/cd_recalls_{n_var}.png', df_perf=recalls_flattened[n_var], title='Recall', labels=False)
    draw_cd_diagram(f'figures/cd_f1s_{n_var}.png', df_perf=f1s_flattened[n_var], title='F1', labels=False)



findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial


findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because

['TD2C' 'TD2C - CMIKNN' 'PCMCI' 'Granger' 'VARLiNGAM']
           Model  count
0        Granger    720
1          PCMCI    720
2           TD2C    720
3  TD2C - CMIKNN    720
4      VARLiNGAM    720
[[0.24358974 0.32471264 0.21791768 ... 0.20456906 0.16777286 0.2046332 ]
 [0.5758547  0.65038314 0.52663438 ... 0.77258567 0.9030236  0.6476834 ]
 [0.49038462 0.79885057 0.50423729 ... 1.         1.         1.        ]
 [0.91880342 0.87691571 0.91646489 ... 1.         1.         1.        ]
 [0.58066239 0.64128352 0.39769976 ... 0.6443406  0.72640118 0.62934363]]
Granger            0.0
PCMCI            162.0
TD2C              76.0
TD2C - CMIKNN    192.0
VARLiNGAM        115.0
dtype: float64
Granger          4.983333
VARLiNGAM        2.687500
TD2C             2.680556
PCMCI            2.466667
TD2C - CMIKNN    2.181944
dtype: float64
('Granger', 'TD2C - CMIKNN', 1.56266813401849e-119, True)
('Granger', 'TD2C', 1.562681705069756e-119, True)
('Granger', 'PCMCI', 1.9655282439095715e-119, True)


findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because

           Model  count
0      DYNOTEARS    720
1        Granger    720
2          PCMCI    720
3           TD2C    720
4  TD2C - CMIKNN    720
5      VARLiNGAM    720
[[0.0625     0.10869565 0.05882353 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.04705882 0.03333333 0.04918033]
 [0.         0.33333333 0.         ... 0.23076923 0.33333333 0.19512195]
 [0.         0.25       0.         ... 0.58064516 0.4        0.2745098 ]
 [0.24137931 0.23333333 0.14705882 ... 0.47368421 0.57142857 0.63636364]
 [0.1        0.0952381  0.01818182 ... 0.15463918 0.21621622 0.15217391]]
DYNOTEARS         20.0
Granger            2.0
PCMCI            186.0
TD2C             160.0
TD2C - CMIKNN    159.0
VARLiNGAM        109.0
dtype: float64
DYNOTEARS        5.135417
Granger          5.060417
VARLiNGAM        2.879861
PCMCI            2.688194
TD2C             2.635417
TD2C - CMIKNN    2.600694
dtype: float64
('Granger', 'TD2C - CMIKNN', 5.42075164491684e-116, True)
('Granger',

findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because

['TD2C' 'TD2C - CMIKNN' 'PCMCI' 'Granger' 'DYNOTEARS' 'VARLiNGAM']
           Model  count
0      DYNOTEARS    720
1        Granger    720
2          PCMCI    720
3           TD2C    720
4  TD2C - CMIKNN    720
5      VARLiNGAM    720
[[0.625      0.55555556 1.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.22222222 0.16666667 0.21428571]
 [0.         0.22222222 0.         ... 0.83333333 1.         0.57142857]
 [0.         0.55555556 0.         ... 1.         1.         1.        ]
 [0.875      0.77777778 0.71428571 ... 1.         1.         1.        ]
 [0.625      0.44444444 0.14285714 ... 0.83333333 0.66666667 0.5       ]]
DYNOTEARS          7.0
Granger           10.0
PCMCI             44.0
TD2C              26.0
TD2C - CMIKNN    106.0
VARLiNGAM        134.0
dtype: float64
DYNOTEARS        5.381250
Granger          4.833333
TD2C             3.012500
PCMCI            2.802083
VARLiNGAM        2.617361
TD2C - CMIKNN    2.353472
dtype: float64
('

findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because

['TD2C' 'TD2C - CMIKNN' 'PCMCI' 'Granger' 'DYNOTEARS' 'VARLiNGAM']
           Model  count
0      DYNOTEARS    720
1        Granger    720
2          PCMCI    720
3           TD2C    720
4  TD2C - CMIKNN    720
5      VARLiNGAM    720
[[0.11363636 0.18181818 0.11111111 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.0776699  0.05555556 0.08      ]
 [0.         0.26666667 0.         ... 0.36144578 0.5        0.29090909]
 [0.         0.34482759 0.         ... 0.73469388 0.57142857 0.43076923]
 [0.37837838 0.35897436 0.24390244 ... 0.64285714 0.72727273 0.77777778]
 [0.17241379 0.15686275 0.03225806 ... 0.26086957 0.32653061 0.23333333]]
DYNOTEARS          1.0
Granger            1.0
PCMCI            207.0
TD2C             132.0
TD2C - CMIKNN    211.0
VARLiNGAM        106.0
dtype: float64
DYNOTEARS        5.350694
Granger          5.027083
VARLiNGAM        2.774306
TD2C             2.722917
PCMCI            2.604167
TD2C - CMIKNN    2.520833
dtype: float64
('

findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because

['TD2C' 'TD2C - CMIKNN' 'PCMCI' 'Granger' 'VARLiNGAM']
           Model  count
0        Granger    720
1          PCMCI    720
2           TD2C    720
3  TD2C - CMIKNN    720
4      VARLiNGAM    720
[[0.20680412 0.14413205 0.0795765  ... 0.22352431 0.17149667 0.09170702]
 [0.51958763 0.54857053 0.4789959  ... 0.83173077 0.87371368 0.71194007]
 [0.54652921 0.43271205 0.58572404 ... 0.99893162 1.         1.        ]
 [0.94687285 0.9486653  0.92682719 ... 1.         1.         1.        ]
 [0.56714777 0.55559943 0.6391735  ... 0.64386351 0.6471701  0.74182809]]
Granger            0.0
PCMCI            198.0
TD2C              88.0
TD2C - CMIKNN    244.0
VARLiNGAM         45.0
dtype: float64
Granger          5.000000
VARLiNGAM        3.078472
TD2C             2.593750
PCMCI            2.357639
TD2C - CMIKNN    1.970139
dtype: float64
('Granger', 'PCMCI', 1.562683401459351e-119, True)
('Granger', 'VARLiNGAM', 1.562683401459351e-119, True)
('Granger', 'TD2C', 1.5626867942441542e-119, True)
('G

findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because

           Model  count
0      DYNOTEARS    720
1        Granger    720
2          PCMCI    720
3           TD2C    720
4  TD2C - CMIKNN    720
5      VARLiNGAM    720
[[0.05970149 0.01714286 0.03317536 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.03636364 0.02197802 0.00378788]
 [0.06666667 0.02857143 0.04166667 ... 0.17218543 0.20175439 0.140625  ]
 [0.28571429 0.         0.         ... 0.40506329 0.28       0.28571429]
 [0.23636364 0.14666667 0.11904762 ... 0.41558442 0.47457627 0.62222222]
 [0.04697987 0.03333333 0.03804348 ... 0.07258065 0.06345178 0.07038123]]
DYNOTEARS         27.0
Granger            1.0
PCMCI            272.0
TD2C             174.0
TD2C - CMIKNN    216.0
VARLiNGAM         12.0
dtype: float64
DYNOTEARS        5.288889
Granger          5.019444
VARLiNGAM        3.744444
TD2C             2.497222
PCMCI            2.359722
TD2C - CMIKNN    2.090278
dtype: float64
('Granger', 'TD2C - CMIKNN', 2.530337659310448e-118, True)
('Granger'

findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because

['TD2C' 'TD2C - CMIKNN' 'PCMCI' 'Granger' 'DYNOTEARS' 'VARLiNGAM']
           Model  count
0      DYNOTEARS    720
1        Granger    720
2          PCMCI    720
3           TD2C    720
4  TD2C - CMIKNN    720
5      VARLiNGAM    720
[[0.26666667 0.23076923 0.58333333 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.25       0.21428571 0.03571429]
 [0.13333333 0.07692308 0.08333333 ... 0.8125     0.82142857 0.64285714]
 [0.13333333 0.         0.         ... 1.         1.         1.        ]
 [0.86666667 0.84615385 0.83333333 ... 1.         1.         1.        ]
 [0.46666667 0.53846154 0.58333333 ... 0.84375    0.89285714 0.85714286]]
DYNOTEARS          9.0
Granger            6.0
PCMCI             52.0
TD2C              41.0
TD2C - CMIKNN     90.0
VARLiNGAM        211.0
dtype: float64
DYNOTEARS        5.540972
Granger          4.723611
TD2C             3.178472
PCMCI            2.817361
TD2C - CMIKNN    2.438194
VARLiNGAM        2.301389
dtype: float64
('

findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because

['TD2C' 'TD2C - CMIKNN' 'PCMCI' 'Granger' 'DYNOTEARS' 'VARLiNGAM']
           Model  count
0      DYNOTEARS    720
1        Granger    720
2          PCMCI    720
3           TD2C    720
4  TD2C - CMIKNN    720
5      VARLiNGAM    720
[[0.09756098 0.03191489 0.06278027 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.06349206 0.03986711 0.00684932]
 [0.08888889 0.04166667 0.05555556 ... 0.28415301 0.32394366 0.23076923]
 [0.18181818 0.         0.         ... 0.57657658 0.4375     0.44444444]
 [0.37142857 0.25       0.20833333 ... 0.58715596 0.64367816 0.76712329]
 [0.08536585 0.06278027 0.07142857 ... 0.13366337 0.11848341 0.1300813 ]]
DYNOTEARS          1.0
Granger            0.0
PCMCI            270.0
TD2C             138.0
TD2C - CMIKNN    275.0
VARLiNGAM         20.0
dtype: float64
DYNOTEARS        5.408333
Granger          5.005556
VARLiNGAM        3.618750
TD2C             2.595833
PCMCI            2.358333
TD2C - CMIKNN    2.013194
dtype: float64
('

findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because

['TD2C' 'TD2C - CMIKNN' 'PCMCI' 'Granger']
           Model  count
0        Granger    720
1          PCMCI    720
2           TD2C    720
3  TD2C - CMIKNN    720
[[0.16161943 0.13472701 0.16504101 ... 0.15591393 0.11379062 0.13426318]
 [0.53073425 0.48279635 0.54557249 ... 0.9018358  0.95060414 0.83844574]
 [0.45704947 0.43060974 0.48534591 ... 0.99983601 1.         1.        ]
 [0.89066604 0.88614003 0.85149746 ... 1.         1.         1.        ]]
Granger            0.0
PCMCI            178.0
TD2C             171.0
TD2C - CMIKNN    241.0
dtype: float64
Granger          4.000000
PCMCI            2.234028
TD2C             1.999306
TD2C - CMIKNN    1.766667
dtype: float64
('Granger', 'PCMCI', 1.562683401459351e-119, True)
('Granger', 'TD2C - CMIKNN', 1.562700365456053e-119, True)
('Granger', 'TD2C', 1.5627156332093284e-119, True)
('PCMCI', 'TD2C - CMIKNN', 3.3149970047028995e-35, True)
('PCMCI', 'TD2C', 1.1534537135411999e-12, True)
('TD2C', 'TD2C - CMIKNN', 8.627903292279256e-06, Tru

findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because

[[0.01303912 0.00729927 0.02105263 ... 0.         0.         0.        ]
 [0.00729927 0.         0.         ... 0.00579374 0.00494805 0.00553506]
 [0.00653595 0.         0.03645833 ... 0.10763889 0.10714286 0.08050847]
 [0.         0.         0.66666667 ... 0.26297578 0.32432432 0.34234234]
 [0.23809524 0.21008403 0.32051282 ... 0.54285714 0.4556962  0.608     ]]
DYNOTEARS         36.0
Granger            0.0
PCMCI            118.0
TD2C             181.0
TD2C - CMIKNN    368.0
dtype: float64
DYNOTEARS        4.489583
Granger          4.069444
PCMCI            2.657639
TD2C             2.184722
TD2C - CMIKNN    1.598611
dtype: float64
('Granger', 'TD2C - CMIKNN', 1.5627851881819336e-119, True)
('Granger', 'PCMCI', 3.262410909149887e-116, True)
('Granger', 'TD2C', 4.072766534166658e-115, True)
('DYNOTEARS', 'TD2C - CMIKNN', 7.812244582450107e-99, True)
('PCMCI', 'TD2C - CMIKNN', 2.0440476261632509e-84, True)
('DYNOTEARS', 'TD2C', 2.528818920871685e-81, True)
('DYNOTEARS', 'PCMCI', 9.72001

findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because

DYNOTEARS          1.0
Granger           23.0
PCMCI            329.0
TD2C              60.0
TD2C - CMIKNN    107.0
dtype: float64
DYNOTEARS        4.722917
Granger          3.741667
TD2C             2.591667
PCMCI            2.005556
TD2C - CMIKNN    1.938194
dtype: float64
('DYNOTEARS', 'TD2C - CMIKNN', 1.3794167026507816e-119, True)
('Granger', 'TD2C - CMIKNN', 4.96477730214633e-116, True)
('DYNOTEARS', 'PCMCI', 2.011063817294881e-111, True)
('DYNOTEARS', 'TD2C', 1.2833978975482574e-108, True)
('Granger', 'PCMCI', 2.7559373814203256e-105, True)
('Granger', 'TD2C', 2.567735134087989e-96, True)
('DYNOTEARS', 'Granger', 3.2304465944651526e-88, True)
('TD2C', 'TD2C - CMIKNN', 9.225263966174825e-33, True)
('PCMCI', 'TD2C', 2.56838934294114e-19, True)
('PCMCI', 'TD2C - CMIKNN', 0.11082305622952893, False)
Index(['DYNOTEARS', 'Granger', 'TD2C', 'PCMCI', 'TD2C - CMIKNN'], dtype='object')
[3, 4]
['TD2C' 'TD2C - CMIKNN' 'PCMCI' 'Granger' 'DYNOTEARS']
           Model  count
0      DYNOTEARS   

findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because none of the following families were found: Arial
findfont: Generic family 'sans-serif' not found because

Index(['DYNOTEARS', 'Granger', 'PCMCI', 'TD2C', 'TD2C - CMIKNN'], dtype='object')


# Combine across N

In [60]:
results_5_vars['td2c_rocs_process']

{10: {0: 0.9497863247863249,
  1: 0.935823754789272,
  2: 0.8493589743589743,
  3: 0.9249394673123487,
  4: 0.8386752136752137,
  5: 0.9443478260869564,
  6: 0.8571428571428571,
  7: 0.829594017094017,
  8: 0.8205128205128205,
  9: 1.0,
  10: 0.8819612590799031,
  11: 0.9303874092009685,
  12: 1.0,
  13: 0.9558111380145278,
  14: 0.9262452107279694,
  15: 0.9880952380952381,
  16: 0.9166666666666667,
  17: 0.8644636015325671,
  18: 0.9150641025641025,
  19: 0.9428418803418803,
  20: 0.9726890756302521,
  21: 0.863984674329502,
  22: 0.9043583535108959,
  23: 0.9246794871794872,
  24: 0.8621794871794872,
  25: 0.8520299145299145,
  26: 0.87590799031477,
  27: 0.8424329501915708,
  28: 0.9727602905569006,
  29: 0.8989104116222759,
  30: 0.8583535108958839,
  31: 0.9152542372881356,
  32: 0.9831932773109243,
  33: 0.9950980392156863,
  34: 0.8824786324786326,
  35: 0.8680555555555556,
  36: 0.8931623931623932,
  37: 0.9929971988795517,
  38: 0.9268162393162392,
  39: 0.8947649572649573},


In [54]:
#[combined_td2c, combined_pcmci, combined_varlingam, combined_dyno
data = {5: results_5_vars, 10: results_10_vars, 25: results_25_vars}
mapping = {'rocs': 'ROC AUC', 'precision': 'Precision', 'recall': 'Recall', 'f1': 'F1-score'}
for metric in ['rocs','precision', 'recall', 'f1']:
    combined_data_across = pd.DataFrame()
    for i, n_var in enumerate([5,10,25]):
        combined_data = combine_data(data[n_var], 'rocs')
        td2c = pd.concat([pd.Series(range((i+1),len(combined_data[0])*(i+1)+1)),pd.Series(['TD2C']*len(combined_data[0])),combined_data[0]], axis=1)
        pcmci = pd.concat([pd.Series(range((i+1),len(combined_data[1])*(i+1)+1)),pd.Series(['PCMCI']*len(combined_data[1])),combined_data[1]], axis=1)
        varlingam = pd.concat([pd.Series(range(1*(i),len(combined_data[2])*(i+1)+1)),pd.Series(['VARLINGAM']*len(combined_data[2])),combined_data[2]], axis=1)
        
        if metric != 'rocs':
            dyno = pd.concat([pd.Series(range(1,len(combined_data[3])+1)),pd.Series(['DYNOTEARS']*len(combined_data[3])),combined_data[3]], axis=1)
            combined_data_across = pd.concat([combined_data_across, td2c, pcmci, varlingam, dyno], axis=0)
        else:   
            combined_data_across = pd.concat([combined_data_across, td2c, pcmci, varlingam], axis=0)

    combined_data_across.columns = ['dataset_name', 'Model', 'Score']
    #reset index
    combined_data_across.reset_index(drop=True, inplace=True)

    print(combined_data_across)
    path = f'cd_{metric}_combined.png'

    draw_cd_diagram(path, df_perf=combined_data_across, title=mapping[metric], labels=False)

    break

       dataset_name Model     Score
0                 1  TD2C  0.949786
1                 2  TD2C  0.935824
2                 3  TD2C  0.849359
3                 4  TD2C  0.924939
4                 5  TD2C  0.838675
...             ...   ...       ...
12949          2156   NaN       NaN
12950          2157   NaN       NaN
12951          2158   NaN       NaN
12952          2159   NaN       NaN
12953          2160   NaN       NaN

[12954 rows x 3 columns]
['TD2C' 'PCMCI' 'VARLINGAM' nan]
       Model  count
0      PCMCI   2160
1       TD2C   2160
2  VARLINGAM   2160
[[0.5758547  0.65038314 0.51958763 ... 0.84084535 0.83903372 0.90408567]
 [0.94978632 0.93582375 0.9214433  ... 0.9984976  0.99818181 0.99868303]
 [0.41239316 0.57423372 0.40817869 ... 0.73654514 0.7652845  0.7688969 ]]


ValueError: Shape of passed values is (3, 2160), indices imply (3, 723)

In [61]:
combined_data_across[719*4:]

dataset_name Model     Score
2876            717  TD2C  0.999811
2877            718  TD2C  0.999937
2878            719  TD2C  0.998454
2879            720  TD2C  0.998827
2880            721  TD2C  0.998498
...             ...   ...       ...
12949          2156   NaN       NaN
12950          2157   NaN       NaN
12951          2158   NaN       NaN
12952          2159   NaN       NaN
12953          2160   NaN       NaN

[10078 rows x 3 columns]